### ISSUE TITLE
SPF check fails when used in dual stack (ipv4 & ipv6) network

### ISSUE THREAD

**Issue by erebe** [viridIT/vSMTP#1032]
**Describe the bug**
When vsmtp is used in dual stack mode, listening in ipv6 and ipv4, spf checks fails when client ip is from an ipv4 only machine.
Take for example this spf check from an email coming from GitHub.
The check fails because the considered client ip is `::ffff:192.30.252.204` which translate in ipv4 to `192.30.252.204`
The `::ffff:192.30.252.204` is not matching/in the SPF of github.com, but 192.30.252.204 should match.
Vsmtp is actually failing the spf check due to the ipv6 translation of the client ip, while it should succeed.

```
github.com.             393     IN      TXT     "v=spf1 ip4:192.30.252.0/22 ... ~all"
```

```
Received-SPF: softfail receiver=erebe-server;
 client-ip=::ffff:192.30.252.204;
 envelope_from=noreply@github.com;
 identity=mailfrom;
 mechanism=all;`
        
Authentication-Results: erebe-server; spf=softfail
 reason="receiver=erebe-server;
 client-ip=::ffff:192.30.252.204;
 envelope_from=noreply@github.com;
 identity=mailfrom;
 mechanism=all;`
        "
 smtp.mailfrom=noreply@github.com
 ```

**To Reproduce**
Configure vsmtp in dual stack mode, and receive an email from an ipv4 only machine
```
  // Specify addresses that the server will listen to.
  config.server.interfaces = #{
    addr: ["[::]:25"],
    addr_submission: [],
    addr_submissions: ["[::]:465"],
  };
```

**Expected behavior**
Spf check should pass instead of failing when an ipv4 is translated to ipv6

**System (please complete the following information):**
- vSMTP version: 2.1.1
- OS: debian
- OS version: bullseye

**Comment by erebe** [comment]
I took a bit of time too much, to look into the issue, and it seems to be coming from `viaspf` lib.

I made a PR to fix the issue, let see if it can be merged
https://gitlab.com/glts/viaspf/-/merge_requests/3
 Support ipv4 mapped to ipv6 address matching

**Comment by ltabis** [comment]
Thank you for your work @erebe, hopefully glts will take a look :D

**Comment by erebe** [comment]
The PR has been merged, but not yet relesead. I asked, but i don't know when he plans to do a new one.

Anyway just to let know that i made a custom build of vsmtp, and the fix in vsmtp seems to fix the issue :)

**Comment by Mathieu-Lala** [comment]
This should fix https://github.com/viridIT/vSMTP/pull/1049

**Comment by erebe** [comment]
I re-updated my own build and indeed it is working now.
You can close the PR if you want :)

P.s: Do you happen to have a PayPal or some way to give a donation ?

**Comment by ltabis** [comment]
> I re-updated my own build and indeed it is working now.
> You can close the PR if you want :)

Awesome !

> P.s: Do you happen to have a PayPal or some way to give a donation ?

We don't have one, but your participation and tests are already of a great help, so thank you very much :)
