### ISSUE TITLE
Support for `.env` files

### ISSUE THREAD

**Issue by Mathieu-Lala** [viridIT/vSMTP#1035]
vSMTP could load `.env` files using the [`dotenv`](https://crates.io/crates/dotenv) crates.

```sh
$> vsmtp --env prod.env
```

**Comment by fa993** [comment]
Hey, I'd be happy to take this up,
Additionally, I noticed we're using the clap crate to parse command line arguments.
That crate has a feature to read values from environment variables if we need to support that as well..

**Comment by Mathieu-Lala** [comment]
Great!

I am not sure if we want to use the clap/env features, we mainly want to expose env variables to the `.vsl` app.

So, *for now*, the implementation is pretty straight forward

* [ ] add an optional `env` clap parameters (and update the tests too)
* [ ] call the `dotenv::from_path` in the `main` function
* [ ] add unit tests to make sure the vsl function [`env`](https://github.com/viridIT/vSMTP/blob/develop/src/vsmtp/vsmtp-rule-engine/src/api/utils.rs#L102) load value from the `.env` file

**Comment by fa993** [comment]
@Mathieu-Lala Hey, I was able to finish the first 2 tasks, but I'm having some difficulty in finishing the last task. Specifically, where should I add the unit test and maybe if you could point me to some other test where I could figure out how to go about implementing the test

**Comment by Mathieu-Lala** [comment]
Most of the tests are located `https://github.com/viridIT/vSMTP/tree/develop/src/vsmtp/vsmtp-test/src/tests`

See the `examples/dnsbl.rs` for example

**Comment by fa993** [comment]
I looked at the tests that you mentioned and they all seem to be using the run_test! macro. I cannot understand how and where I can call `dotenv::from_path` function to make sure the environment variables are set

**Comment by Mathieu-Lala** [comment]
Right, here is how https://github.com/viridIT/vSMTP/blob/develop/src/vsmtp/vsmtp-test/src/tests/protocol/mail_from.rs#L51

```rs
#[test_log::test(tokio::test(flavor = "multi_thread", worker_threads = 2))]
fn dotenv() {
  ...

  run_test! {
    ...
  }
}
```

**Comment by fa993** [comment]
Hey, @Mathieu-Lala I just realised I won't be able to finish these changes since I can't actually test this on my local machine. This application only works on Windows and Linux systems. :(

**Comment by Mathieu-Lala** [comment]
No problem, open a pull request and i will finish this

**Comment by fa993** [comment]
> No problem, open a pull request and i will finish this

Done

**Comment by Mathieu-Lala** [comment]
Done here #1039
