### ISSUE TITLE
Can't make DKIM config work

### ISSUE THREAD

**Issue by julienmarie** [viridIT/vSMTP#1066]
**Describe the bug**
I'm getting an error message when setting a DKIM private key 
Here is the error I get

```
Could not get configuration for the 'xxx.xxx.com' domain because: No writable property 'private_key' - a setter is not registered for type '()' to handle 'array' (line 2, position 15)
in call to function 'on_domain_config'..
vSMTP terminating error: 'Cannot parse the configuration'
because: No writable property 'private_key' - a setter is not registered for type '()' to handle 'array' (line 2, position 15)
in call to function 'on_domain_config'
```

**To Reproduce**

I'm following the instructions here: https://vsmtp.rs/tuto/3/dkim.html

```
fn on_domain_config(config) {
  config.dkim.private_key = ["/path/to/private-key-1", "/path/to/private-key-2", ...];
  config
}
```
**Expected behavior**

No error messge

**System (please complete the following information):**
- vSMTP version: 2.1.1
- OS: Ubuntu
- OS version: 22.04

**Comment by Mathieu-Lala** [comment]
Can you try this syntax ?
```txt
   config.dkim = #{
        private_key: [ "/path1", "/path2" ],
    };
```

**Comment by julienmarie** [comment]
Great this work. But now signing with dkim doesnt work when I send an email:

my config:

```
postq: [
    action "sign dkim" || {

      for key in dkim::get_private_keys("sub.domain.com") {
        dkim::sign(
          // Selector of the DNS record.
          "_dkim_mta",
          // The private key associated with the public key in `{selector}._domainkey.{sdid}`
          key,
          // Headers to sign with.
          ["From", "To", "Date", "Subject", "From"],
          // Canonicalization algorithm to use.
          "simple/relaxed"
        );
      }
    }
  ],
}
```

```023-03-13T04:34:56.791791Z ERROR error=vsl execution produced an error: Function not found: dkim::sign (&str | ImmutableString | String, alloc::sync::Arc<vsmtp_auth::dkim::private_key::PrivateKey>, array, &str | ImmutableString | String) (line 6, position 15)
in closure call
2023-03-13T04:34:56.791832Z  WARN error while executing directive returning: Deny(Left(Denied)) e=vsl execution produced an error: Function not found: dkim::sign (&str | ImmutableString | String, alloc::sync::Arc<vsmtp_auth::dkim::private_key::PrivateKey>, array, &str | ImmutableString | String) (line 6, position 15)
in closure call```

**Comment by Mathieu-Lala** [comment]
This chapter of the documentation has not been updated for the latest version.

You can see a valid example here : https://vsmtp.rs/next/ref/vSL/api/fn::global::dkim.html#example

**Comment by Mathieu-Lala** [comment]
Could you fix your problem ?

**Comment by julienmarie** [comment]
Yes the DKIM is ok now.

But I still can't send emails.

```
2023-03-15T03:57:04.126892Z  WARN error=TlsNoCertificate

2023-03-15T03:57:04.126901Z  WARN Some send operations failed, email MoveToDeferred.

```

It would be great to have a basic base configuration example, but I'll try to dig into the documentation more deeply. It seems really powerful but learning curve is quite steep.

( Use case: newsletter sending server ).

*Julien Marie*

***@***.***
skype : thewiseup
+63 917 511 8258

Schedule a meeting here: https://calendar.x.ai/j

-----BEGIN PGP PUBLIC KEY BLOCK-----

xsBNBFNmiRIBCAC77MQjKyaDaRo9bQhfGNXIDK3SldtI+A56EAY2xh8/WCrJ
HYwhdwW/2aConIa5eL92WLf0W6FSmjk0rqSp1bkkDt8RW7JFiftCACZkSwHF
Rg3zpUeMgFG3BBRpwCiOxSygDza61AmMAQ+8LuLZOETEFddT/DQNCBouZLYN
KE9uCs+lYkrpc3YbPfx+kGUDj5rT2SYnHwt4r352OjT1U8ABQdxBigymmzgT
rZh/4oyVXjMtBCRwAqwmVtzwoNoarAcgsm6qQgNwTdy5NtmKlgs2hqQtIkQK
3uL+e3zyWb1B8e6gUhpn5cooeJG1hvlJ65XUTHgHOCCz7Ue4q1rl/5kZABEB
AAHNIEp1bGllbiBNYXJpZSA8am1AcHJvZHVjdHVyZS5jb20+wsByBBABCAAm
BQJTZokZBgsJCAcDAgkQ7nj49Sxgl2gEFQgCCgMWAgECGwMCHgEAANulB/4u
c+UeSeo8Wn8COAKSoMyWh2m5zBEdRdTlELVNcQIH3ssqu1M3TEpfBixVofp2
NPYKNF7FrQPl7z9+w0azlVJVIDF6DlGWjVlKm1nDTlVr4gW8J6mgRYivV3Tp
HlBHIFmelOIcBpJAhUfc73H5a9BAsJ/a2Iekpc0TERsnarVuA3sqeTqPkwBY
komURJWx0yxiYj91Be1PDRRi+DyGBKa8AeapXiCmCtpGAxksB43iwiiFnLev
iZCWp3bKeBCLZy5IkONNU6mNzTcljrgHzRjs9P8OSiEIJ9T8tubHUkkA0LsR
9l7vmBk3aESNF8w1LmRTRN+gBkXsMSjzNilGj7zBzsBNBFNmiRkBCACOsST4
AuZffy8Ny7w1Qhvo1Okt9bBoh5zIJKE0tEo1L4YmDYALKnagVHNUwiAM26Bv
ynK+pAvRopt62Wu+s1hQgHNuwnTMuuL0OW4Y8daOIN9pUAqnT/etskSwH24W
niP445IEa09RyA1b2Mwhy8hEN/eCFHmnY36U5+qiiUAjN6Khsflzkq4I2Qy9
wwMVhNC8/J1QtmODcUekMgnGG0XcXNm22N1EU3llr5yG/oYD0dAKnIIv4rf8
3s6LU7ND/SOjmaLNtzwLuGawcCBPGfaBpB77ozJz0jJ3RaEwuY/Kqt4Zfp5T
0xLFgr+fXxSjHku0qU6PGT3iH+eHkWZXGG2pABEBAAHCwF8EGAEIABMFAlNm
iRwJEO54+PUsYJdoAhsMAADWtwf9HJiym4Oi2zwWiDksmLc7699iVY1pvuic
RlqwMw2bmFd+PUUFupU6CR8jOTcYPJm3NzZ9gwPM3yzjd/BReWmd4mfZJfvf
EIYHzJoDRmnT5t8b9Wp6jllWtVAHbN9FTUW3uJODDKhffhYNbmAhxpotao+a
XQJcSrcWE1Gl030ZQryOfkz2l/eUfYYSK38gsR7ksz22Gb1CKS4gmG8jgxQs
vmDTSRagUYEXOdTaX5HKMdHrMw1ll1Z8bMb/y0N0kgDmIF0pAX2i+bk5UpnU
6mbeLCwo0OoIPYpC4GvGPBglull+BRJlwvf9Kpzlip5KHYSTnb19yyjbs1qC
rpsqrnUA6g==
=o6AX
-----END PGP PUBLIC KEY BLOCK-----

**Comment by Mathieu-Lala** [comment]
The issue you are having now has been fixed, you can already try it with docker [`viridit/vsmtp:unstable`](https://hub.docker.com/repository/docker/viridit/vsmtp).

We will do a proper release soon
