### ISSUE TITLE
DKIM issue

### ISSUE THREAD

**Issue by xoraingroup** [viridIT/vSMTP#1159]
vsmtp v2.2.1
commit: 5ab457489c292f36b646cd3a3cad54da4de4cd4d

using following in outgoing.vcl for our domain
```
#{
  authenticate: [
    rule "sasl authentication" || auth::unix_user(),
  ],

  mail: [
    rule "deny unauthenticated" || {
      if auth::is_authenticated() {
        state::next()
      } else {
        state::deny(code(530, "5.7.0", "Authentication required\r\n"))
      }
    }
  ],

  preq: [
    action "sign dkim" || {
      for private_key in dkim::get_private_keys("mydomain.com") {
        dkim::sign(#{
           // default: server_name()
           sdid:                "mydomain.com",

           // mandatory
           selector:            "jun2021",

           // mandatory
           private_key:         private_key,

           // default: ["From", "To", "Date", "Subject", "From"]
           headers:             ["From", "To", "Date", "Subject", "From"],

           // default: "simple/relaxed"
           canonicalization:    "simple/relaxed"
        });
      }
    },
    rule "verify dkim" || {
      dkim::verify();

      // The dkim header should indicate a pass.
      if !msg::get_header("Authentication-Results").contains("dkim=pass") {
        return state::deny();
      }

      // the result of dkim verification is cached, so this call will
      // not recompute the signature and recreate a header.
      dkim::verify();

      // FIXME: should be one.
      if msg::count_header("Authentication-Results") != 2 {
        return state::deny();
      }

      state::accept()
    }
  ],
}
```

DKIM loaded in domain config.

```
fn on_domain_config(config) {

  config.tls = #{
	certificate: "/etc/certs/fullchain.pem",
    	private_key: "/etc/certs/privkey.pem",
  };

  config.dkim = #{
    private_key: ["/etc/certs/dkim.key"],
  };

  config

}
```

Error in logs.

```
2023-04-27T04:53:52.752577Z ERROR serve:rule:execute: error=vsl execution produced an error: Output type incorrect: alloc::sync::Arc<vsmtp_auth::dkim::private_key::PrivateKey> (expecting rhai::types::dynamic::Dynamic)
in closure call uuid=f24e9aa3-3e40-4d43-b8ee-b0ea5c9cf2eb stage=preq self=action { name: "sign dkim", .. }
```

Any quick way to fix this?

**Comment by ltabis** [comment]
Hey, thanks for the report. I believe we already fixed this issue for the next release. In the meantime, you can use the following code for your "sign dkim" rule:

```js
action "sign dkim" || {
  for private_key in dkim::get_private_keys("mydomain.com") {
    dkim::sign(#{
      // default: server_name()
      sdid:                "mydomain.com",
      
      // mandatory
      selector:            "jun2021",
      
      // mandatory
      private_key:         private_key,
      
      // default: ["From", "To", "Date", "Subject", "From"]
      headers:             ["From", "To", "Date", "Subject", "From"],
      
      // default: "simple/relaxed"
      canonicalization:    "simple/relaxed"
    });
  }

  () // I added this !
},
```
In the next version, the unit type `()` won't be mandatory in an `action` return statement.

**Comment by xoraingroup** [comment]
Thank you for this, now that issue is gone, but I am getting following issue

```
error while executing directive returning: Deny(Reply { code: Code { code: 554 }, text: ["permanent problems with the remote server"], folded: "554 permanent problems with the remote server\r\n" })
Apr 27 07:24:05 smtp-de-01 vsmtp[12902]: The rule engine will skip all rules because of the result Deny(Reply { code: Code { code: 554 }, text: ["permanent problems with the remote server"], folded: "554 permanent problems with the remote server\r\n" })
```

**Comment by ltabis** [comment]
Seems to be another problem, I'm working on a fix

**Comment by xoraingroup** [comment]
I will be waiting for update. Thank you for your time.

**Comment by ltabis** [comment]
Hey @xoraingroup, I have identified where the problem comes from. Unfortunately, the way we did the above dkim sign workflow is pretty much "unfixable" at the time, without going through a breaking change. In the future releases, we will introduce a breaking change that will remove the `for` loop needed to fetch the keys from the config in the current version. Only a simple call to `dkim::sign` will be necessary. 

If someone else find an alternative solution to fix it fast before a breaking change I'll keep you posted.

I'll keep this open for the time being, thanks again for the report !

**Comment by schungx** [comment]
I wonder why the `for` loop should be causing problems... just curious.

**Comment by ltabis** [comment]
> I wonder why the for loop should be causing problems... just curious.

The parameter of the `dkim::sign` function is a `rhai::Map` that we deserialize [here](https://github.com/viridIT/vSMTP/blob/develop/src/vsmtp/vsmtp-rule-engine/src/api/dkim.rs#L437) into [this struct](https://github.com/viridIT/vSMTP/blob/develop/src/vsmtp/vsmtp-rule-engine/src/api/dkim.rs#L34).
 
I read that [rhai cannot deserialize shared values](https://rhai.rs/book/rust/serde.html?highlight=deseri#admonition-cannot-deserialize-shared-values) yesterday, and unfortunately the `private_key` parameter is one (although we use `no_closure`, it is because the internal key representation is wrapped in a `Box`).

@schungx the failing code is triggered [here](https://github.com/viridIT/vSMTP/blob/develop/src/vsmtp/vsmtp-rule-engine/src/api/dkim.rs#LL50C28-L50C28). If you have an idea of a fix, I'll be glad to take it. I think I am missing something with the deserialization of shared values ...

**Comment by schungx** [comment]
> I read that [rhai cannot deserialize shared values](https://rhai.rs/book/rust/serde.html?highlight=deseri#admonition-cannot-deserialize-shared-values) 

Can you `flatten` the shared value before you deserialize?

**Comment by xoraingroup** [comment]
> Hey @xoraingroup, I have identified where the problem comes from. Unfortunately, the way we did the above dkim sign workflow is pretty much "unfixable" at the time, without going through a breaking change. In the future releases, we will introduce a breaking change that will remove the `for` loop needed to fetch the keys from the config in the current version. Only a simple call to `dkim::sign` will be necessary.
> 
> If someone else find an alternative solution to fix it fast before a breaking change I'll keep you posted.
> 
> I'll keep this open for the time being, thanks again for the report !

Yes that should be ok. I was more of reporting more bugs as i would be testing, but i will wait for the release and then test and report bugs.

Thank you for your time.

**Comment by schungx** [comment]
@ltabis   The following test passes for the latest Rhai master drop:
```rust
#[test]
fn test_serde_de_variants() -> Result<(), Box<EvalAltResult>> {
    #[derive(Debug)]
    struct Foo;

    #[derive(Debug, Deserialize)]
    struct Bar {
        #[serde(deserialize_with = "deserialize_foo")]
        value: Arc<Foo>,
    }

    fn deserialize_foo<'de, D: Deserializer<'de>>(deserializer: D) -> Result<Arc<Foo>, D::Error> {
        let value = <Dynamic as Deserialize>::deserialize(deserializer)?;

        value
            .try_cast::<Arc<Foo>>()
            .ok_or_else(|| serde::de::Error::custom("type error"))
    }

    let value = Arc::new(Foo);
    let mut map = Map::new();
    map.insert("value".into(), Dynamic::from(value.clone()));
    let x = Dynamic::from(map);
    let bar = from_dynamic::<Bar>(&x)?;

    assert!(Arc::ptr_eq(&bar.value, &value));

    Ok(())
}
```

**Comment by ltabis** [comment]
Thanks for your work @schungx, I can't really test it because rhai-dylib does not uses the master branch, I'll have to wait a little bit.

**Comment by schungx** [comment]
No prob! I'd see if I can release a new version to crates.io soon so you don't have to pull from github.

**Comment by ltabis** [comment]
This issue has been fixed in https://github.com/viridIT/vSMTP/pull/1171, i'll close this now !
