### ISSUE TITLE
`vqueue` cannot show messages

### ISSUE THREAD

**Issue by korrat** [viridIT/vSMTP#1252]
**Describe the bug**
Due to a possible bug, I have over 5000 messages in the dead folder, but whenever I try to check for details of any of these messages, I get the following error from vqueue:

```
$ vqueue msg 7f107ed1-39a3-40d2-8847-057d4087bccd show
Error: Mail context not found
```

**Expected behavior**
I would expect the command to show me some information about the message.

**System (please complete the following information):**
- vSMTP version:
  ```
  vqueue v2.2.1
  commit: 5ab457489c292f36b646cd3a3cad54da4de4cd4d
  ```
- OS: `Linux mail.korr.at 5.10.0-23-amd64 #1 SMP Debian 5.10.179-1 (2023-05-12) x86_64 GNU/Linux`

**Comment by ltabis** [comment]
We just released the first release candidate for vSMTP v3.0, and vqueue as been replaced by RabbitMQ, so I am closing this.
