### ISSUE TITLE
VSL : message body manipulation #1

### ISSUE THREAD

**Issue by Mathieu-Lala** [viridIT/vSMTP#151]
Using the rule engine, you can apply modification to a message.

The following should be possible :

* [x] `add_header(key, value)` : add (or update) a header field of the message
* [x] `bcc(rcpt)` : add a recipient to the Blind Carbon Copy of the message

**Comment by ltabis** [comment]
merge of #149 needs to be done before doings tests for `add_header` & `bcc`
