### ISSUE TITLE
Mime parsing fail message

### ISSUE THREAD

**Issue by ltabis** [viridIT/vSMTP#208]
### Discussed in https://github.com/viridIT/vSMTP/discussions/83

<div type='discussions-op-text'>

<sup>Originally posted by **ltabis** January 18, 2022</sup>
For now, incoming emails are stored in the `MailContext` struct using the following enum:

```rust
pub enum Body {
    Raw(String),
    Parsed(Box<crate::mime::mail::Mail>),
}
```
That does not indicate if parsing failed.

I suggest that we add another field to the enum.

```rust
use crate::mime::error::ParserError;

pub enum Body {
    Raw(String),
    Parsed(Box<crate::mime::mail::Mail>),
    ParsingFailed { raw: String, reason: ParserError },
}
```
- `raw` is the whole email as a raw string.
- `reason` is the reason why parsing failed using the ``ParserError`` enum.

That way, the rule engine could react accordingly, preventing rewrites for example. We could also create a specific action to test if the parsing was successful or not.
</div>

**Comment by Mathieu-Lala** [comment]
Outdated, but the idea will be implemented soon
