### ISSUE TITLE
Get rid of openssl dependency

### ISSUE THREAD

**Issue by drahnr** [viridIT/vSMTP#399]
**Is your feature request related to a problem? Please describe.**
Currently due to trust-dns, it's required to link openssl. This has is a common pain when building for minimal containerized environments.

**Describe the solution you'd like**
Remove the openssl dependency :) this is obviously a larger task.

**Describe alternatives you've considered**
Make it work with openssl, compile it statically from source, and link that statically.

**Comment by ltabis** [comment]
As you said, this is not going to be feasible any time soon. It's too huge of a task for the estimated gains.
Can you suggest any replacement, or should the right way would be to redo openssl by hand ?

I'll keep this open as it could be interesting to remove that dependency to prevent linking.

**Comment by Mathieu-Lala** [comment]
```sh
$> ldd ./target/debug/vsmtp
        linux-vdso.so.1 (0x00007ffcccf6e000)
        libgsasl.so.7 => /lib/x86_64-linux-gnu/libgsasl.so.7 (0x00007fb3c8327000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fb3c830c000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fb3c82ea000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fb3c819c000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fb3c8195000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fb3c7fa9000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fb3ca972000)
        libidn.so.11 => /lib/x86_64-linux-gnu/libidn.so.11 (0x00007fb3c7f72000)
        libntlm.so.0 => /lib/x86_64-linux-gnu/libntlm.so.0 (0x00007fb3c7f68000)
        libgssapi_krb5.so.2 => /lib/x86_64-linux-gnu/libgssapi_krb5.so.2 (0x00007fb3c7f14000)
        libkrb5.so.3 => /lib/x86_64-linux-gnu/libkrb5.so.3 (0x00007fb3c7e3c000)
        libk5crypto.so.3 => /lib/x86_64-linux-gnu/libk5crypto.so.3 (0x00007fb3c7e0c000)
        libcom_err.so.2 => /lib/x86_64-linux-gnu/libcom_err.so.2 (0x00007fb3c7e03000)
        libkrb5support.so.0 => /lib/x86_64-linux-gnu/libkrb5support.so.0 (0x00007fb3c7df4000)
        libkeyutils.so.1 => /lib/x86_64-linux-gnu/libkeyutils.so.1 (0x00007fb3c7ded000)
        libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007fb3c7dd2000)
```
Seems about right ! (https://github.com/viridIT/vSMTP/pull/446)

**Comment by Mathieu-Lala** [comment]
The pr has been merged, you can use `develop` or the next release `1.1.4` it should comes by the end of the week
