### ISSUE TITLE
Allow logging to stdout/stderr, configurable log file

### ISSUE THREAD

**Issue by drahnr** [viridIT/vSMTP#404]
**Is your feature request related to a problem? Please describe.**
For most external logging systems, it's customary to grab the stdout/stderr output.

**Describe the solution you'd like**
By default, log to stdout when running `--no-daemon` and allow overrides via i.e. `--log`

**Comment by ltabis** [comment]
In what context would you want to redirect the logs output ? Do you need this for docker ?

**Comment by drahnr** [comment]
Any deployment platform using containers as base unit handles stdout / stderr logging by default. File based logging less/not common in those environments.

**Comment by ltabis** [comment]
Well, logs are already automatically sent to stdout in `--no-daemon` mode.
Or are you meaning that you want to chose between `stdout` or `stderr`, not only `stdout` ?

**Comment by drahnr** [comment]
I tried with a binary compiled from a guy checkouts from earlier last week, and it wasn't the case when deploying in a container (getting permission denied at al)

**Comment by ltabis** [comment]
Hey! I made a PR (#406) that fixes the issue of rolling files that get created even though you set the `--no-daemon` option. It will be available for the next release. You should not have permission error after that fix.

**Comment by ltabis** [comment]
You can pull develop to make your own tests before the next release if you want to!
