### ISSUE TITLE
Customize log format

### ISSUE THREAD

**Issue by Mathieu-Lala** [viridIT/vSMTP#470]
With `tracing` it is possible to change the format of the generated output.
This format should be customization in the configuration

**Comment by paguardiolle** [comment]
Before production release:
1) Review error/warn and info levels. Not enough information (warn) and/or too much. 
2) Follow historical guidelines In "TXT" mode the default. Output must be more concise (except for trace and debug). 
3) Follow Unix FHS and best practices : vSMTP main log files must be in /var/log/vsmtp w/o a timestamp (ie vsmtp.log and app.log) - ok for the archives in subdirectoris
4) Syslog : there must be an option (goal : logs in /var/log/mail.log and mail.err)
