### ISSUE TITLE
ARMv7 support

### ISSUE THREAD

**Issue by paguardiolle** [viridIT/vSMTP#532]
Compiling vsmtp-rsasl v1.5.1-rc2
error[E0606]: casting `&mut u8` as `*mut i8` is invalid
  --> /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/vsmtp-rsasl-1.5.1-rc2/src/buffer.rs:86:29
   |
86 |         unsafe { gsasl_free(Box::leak(self.ptr) as *mut i8 as *mut libc::c_void) };
   |                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0308]: mismatched types
   --> /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/vsmtp-rsasl-1.5.1-rc2/src/session.rs:130:52
    |
130 |             Some(unsafe { std::ffi::CStr::from_ptr(ptr as *mut i8) })
    |                           ------------------------ ^^^^^^^^^^^^^^ expected `u8`, found `i8`
    |                           |
    |                           arguments to this function are incorrect
    |
    = note: expected raw pointer `*const u8`
               found raw pointer `*mut i8`
note: associated function defined here

Some errors have detailed explanations: E0308, E0606.
For more information about an error, try `rustc --explain E0308`.

**Comment by Mathieu-Lala** [comment]
Has been fixed on `develop` with #536 ; drafter for release v1.3.0-rc.1
