### ISSUE TITLE
Wildcard virtual domains for catch-all addresses.

### ISSUE THREAD

**Issue by dequbed** [viridIT/vSMTP#567]
**Is your feature request related to a problem? Please describe.**

I'm currently looking at what vSMTP would need to provide for us to be able to switch over to it.

**Describe the solution you'd like**

We're currently using the PCRE-"database" of postfix to implement ad-hoc catch-all domains. i.e. every user in our network can have mail sent to \<arbitrary string\>@\<username\>.\<domain\>.\<tld\>, as sub-addresses using "+" aren't accepted by all forms.

**Describe alternatives you've considered**

¯\\\_(ツ)\_/¯

**Additional context**

http://www.postfix.org/pcre_table.5.html

**Comment by Mathieu-Lala** [comment]
Do you wish to use PCRE like database in vSMTP ?
Or is it just a mean to handle alias like `<token>@<mailbox>.<domain>   ->   <mailbox>@<domain>` ?

**Comment by dequbed** [comment]
My case really only needs to be able to rewrite recipient addresses from the form `<token>@<mailbox>.<domain>.<tld>` to `<mailbox>@<different-domain>.<tld>`, so we don't really need to full power of PCRE, or regex to begin with.

**Comment by Mathieu-Lala** [comment]
This is possible with the latest changes :

```txt
/etc/vsmtp
   ├─ vsmtp.vsl
   └─ domain-avaible
       ├─  incoming.vsl
       └─  mydomain.com
                └─ incoming.vsl
```              
  
```js
// in /etc/vsmtp/vsmtp.vsl
fn on_config(config) {
  config.server.interfaces = #{
    addr: ["127.0.0.1:25"],
  };

  config
}
```
  
```js
// in /etc/vsmtp/domain-available/incoming.vsl
#{  } // this is an empty map
```
  
```js
// in /etc/vsmtp/domain-available/mydomain.com/incoming.vsl
#{
  rcpt: [
        action "rewrite mail from" || {
            let target_domain = "mydomain.com";

            // let token = rcpt().local_part; // <token>
 
            let input_domain = rcpt().domain.to_string(); // <mailbox>.<domain>.<tld>
            input_domain.truncate(input_domain.len - target_domain.len - 1); // <mailbox>

            rewrite_rcpt_envelop(rcpt(), `${input_domain}@${target_domain}`); // <mailbox>@<domain>.<tld>
        }
  ]
}
```

We will make a release very soon, with a proper documentation about the code above :heavy_check_mark:

**Comment by Mathieu-Lala** [comment]
The release v2.0 contains the fix of this issue, let me know if you face any problem :+1: 
I close this issue for now
