### ISSUE TITLE
LDAP DB support

### ISSUE THREAD

**Issue by dequbed** [viridIT/vSMTP#568]
**Is your feature request related to a problem? Please describe.**

I'm currently looking at what vSMTP would need to provide for us to be able to switch over to it.

**Describe the solution you'd like**

We perform three LDAP searches in our postfix. The first one is to check if an user has set a mail forward; in which case all mail received for that person is immediately forwarded. The second lookup maps recipient addresses to an account for rcpt rewriting. The final one is to do validate on sending that an user is not sending from an address they don't own.

As far as I can tell the actual rewriting and all of that is already possible with rules and vSL, so this really only needs a reasonable way to send a query to a LDAP server.

**Comment by paguardiolle** [comment]
LDAP is planned in the next release (v1.4)... somewhere/somewhen in september. (v1.3.0 tomorrow w/ MySQL, aarch64 and a lot of fix!)

We will be very happy to help you rewriting in vSL yours rules, so don't hesitate to contact us on Discord.

Rgds

**Comment by ltabis** [comment]
Hey @dequbed !

vSMTP 2.0 is out,introducing a plugin system enabling support for third-party software.

I'm working on a LDAP plugin, you can check my progress here: https://github.com/viridIT/vSMTP/pull/928
Do not hesitate to comment the PR above if some feature are missing !

**Comment by ltabis** [comment]
Hey @dequbed,

We just finished to develop a ldap plugin, it will be live once the next release comes out.
