### ISSUE TITLE
SpamAssassin Integration

### ISSUE THREAD

**Issue by steakhouse** [viridIT/vSMTP#577]
Is it / will it be possible to integrate SpamAssassin?
At first glance I could not find anything regarding Anti-Spam.

Thanks!

**Comment by ltabis** [comment]
@steakhouse There is a greylist example [here](https://github.com/viridIT/vSMTP/tree/develop/examples/greylist) and a DNSBL example [here](https://github.com/viridIT/vSMTP/tree/develop/examples/dnsbl) that can help you fight spamming for now.
Anyways, including spam assassin would be awesome, I don't know yet how it works but I'll definitely keep that in mind for future releases !

**Comment by paguardiolle** [comment]
WWe are working on milter support. So native integration will come soon.
Nevertheless you can integrate SpamAssassin into vSMTP using spampd "smtp proxy" (a spamd replacement that works as a SMTP-proxy, thanks to the guys @worlddesign.com). The procedure for vSMTP is the same as clamAV (smtp delegation).

Imho it's the best solution as you can use preq or postq filtering.

Here is the postfix procedure;
https://cwiki.apache.org/confluence/display/SPAMASSASSIN/IntegratePostfixViaSpampd

Link to vSMTP delegation:
https://vsmtp.rs/tuto/0/antivirus.html

We didn't test it anyway and we will be happy to have your feedback.

**Comment by steakhouse** [comment]
Thanks! Great replies on both stances.
