### ISSUE TITLE
MongoDB support as vsl service/databases

### ISSUE THREAD

**Issue by Brandl** [viridIT/vSMTP#619]
**Is your feature request related to a problem? Please describe.**
As mentioned in #91 I would love to write incoming emails to MongoDB via vsl and check incoming emails TO against MongoDB.
MongoDB offers great interoperability with other software stacks and would be a nice addition as a NoSQL DB to the currently supported MySQL.

**Describe the solution you'd like**
A vsl service that implements an interface to MongoDB.

**Describe alternatives you've considered**
Alternatively one could probably achieve the same end goal using redis or rabbitmq.

**Additional context**

I'm writing this issue mainly as a way for myself to track progress on the feature request. Feel free to implement this as you see fit.

**Comment by ltabis** [comment]
Hey @Brandl, we are implementing a plugin system which will enable us to add third party software and libraries to vSTMP. We haven't yet decided to implement MongoDB with this system, but that could be doable !

**Comment by ltabis** [comment]
> Whats the progress on the plugin system?

It is finished but only available on the develop branch for the time being.

> It looks like the existing plugins have been in private repos for a while.

Yes, I have a lot of documentation to do so I let them private while I'm working on that.

> Is it in a state, where I as a rust noobie would be able to implement something like that myself?

We use the https://github.com/rhaiscript/rhai-dylib crate (which I also maintain) to implement plugins for vSMTP. Honestly, except for a few pitfalls, you should be fine if you want to make your own.

You will basically have to use a rust driver for mongodb (like this one https://github.com/mongodb/mongo-rust-driver) and expose it's API using the Rhai programming language (what we use for filtering), compile that to a dynamic library, and it will be done. Making a MySQL plugin & CSV plugin was a piece of cake. 
 
Documentation is on it's way, but the paragraph above resumes what you have to do to build you own plugin. I'll keep you posted.

**Comment by ltabis** [comment]
Hey @Brandl, we are working on a mongo db plugin in https://github.com/viridIT/vSMTP/pull/1034 :smiley:
