### ISSUE TITLE
Error: deliver smtp stage does not exist

### ISSUE THREAD

**Issue by yonas** [viridIT/vSMTP#623]
I tried setting up a [basic configuration](https://vsmtp.rs/tuto/0/basic.html#basic-configuration), but I got this error:

`2022-09-26T23:56:18.708003Z ERROR error="vSMTP terminating error: 'the 'deliver' smtp stage does not exist.'"`

**Comment by yonas** [comment]
This should be fixed with https://github.com/viridIT/vBook/pull/43

**Comment by ltabis** [comment]
Good catch ! Fixed with https://github.com/viridIT/vBook/pull/43
