### ISSUE TITLE
Create `cur` folder in Maildir

### ISSUE THREAD

**Issue by yonas** [viridIT/vSMTP#626]
https://github.com/viridIT/vSMTP/blob/749dc417f68709f31d7ed87b77568fd4f207880c/src/vsmtp/vsmtp-delivery/src/transport/maildir.rs#L113-L126

----- **Edit** ----- I meant to say `cur`.
neomutt will not recongnize the folder as a proper Maildir if the `cur` directory is missing.

I don't know Rust, but can we do a simple `if` check and create the `cur` directory if it doesn't exist?

**Comment by ltabis** [comment]
> I don't know Rust, but can we do a simple if check and create the new directory if it doesn't exist?

Actually this is what vSMTP does in the code above, could you enable logs with at least the "debug" level ? The message telling you that the folder already exists is locked behind a debug level message. Also, did you get a permission error in your logs ? It's possible that if you have created the Maildir folder by hand, that vSMTP does not have the necessary permissions to write in that folder.

**Comment by Mathieu-Lala** [comment]
We used to consider that it is not the role of the MTA to ensure his ecosystem has been initialized well.
Should vSMTP (as a MTA) create a folder `/home/{user}/Maildir/cur` (even tho vSMTP does not use this folder) ?

**Comment by yonas** [comment]
I think vSMTP is responsible for creating the three folders if it finds that any of the default folders, `new`, `cur`, or `tmp`, are not present.


> A “maildir” is a directory that's created by [maildirmake](https://manpages.ubuntu.com/manpages/kinetic/man1/maildirmake.1.html).
> ...
> A maildir contains three subdirectories: tmp, new, and cur. These three subdirectories comprise the primary folder, where new mail is delivered by the system.
> 
-- [maildir.courier.5](https://manpages.ubuntu.com/manpages/kinetic/man5/maildir.courier.5.html)

How qmail created Maildir folders: https://github.com/amery/qmail/blob/master/maildirmake.c

```
#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include "strerr.h"
#include "exit.h"

#define FATAL "maildirmake: fatal: "

int main(argc,argv)
int argc;
char **argv;
{
  umask(077);
  if (!argv[1])
    strerr_die1x(100,"maildirmake: usage: maildirmake name");
  if (mkdir(argv[1],0700) == -1)
    strerr_die4sys(111,FATAL,"unable to mkdir ",argv[1],": ");
  if (chdir(argv[1]) == -1)
    strerr_die4sys(111,FATAL,"unable to chdir to ",argv[1],": ");
  if (mkdir("tmp",0700) == -1)
    strerr_die4sys(111,FATAL,"unable to mkdir ",argv[1],"/tmp: ");
  if (mkdir("new",0700) == -1)
    strerr_die4sys(111,FATAL,"unable to mkdir ",argv[1],"/new: ");
  if (mkdir("cur",0700) == -1)
    strerr_die4sys(111,FATAL,"unable to mkdir ",argv[1],"/cur: ");
  return 0;
}
```

The problem with qmail's approach here is that it will fail if any of the three folder's already exist. That's quite brittle. I recommend doing a simple check before running `mkdir`.

**Comment by Mathieu-Lala** [comment]
Let me know if it is working fine now :+1:

**Comment by yonas** [comment]
It works! :partying_face: :+1:
