### ISSUE TITLE
certificate path is valid but empty

### ISSUE THREAD

**Issue by thomas-mc-work** [viridIT/vSMTP#692]
**Describe the bug**

Somehow reading my certificate files always fails. This is the error message that I get:

    vSMTP terminating error: 'Cannot parse the configuration'
    because: File contains format error
    because: certificate path is valid but empty: '/data/ssl/mydomain.org.pem' for key `server.tls.certificate` at line 23 column 1

**To Reproduce**

I've followed the tutorial up to this step: https://vsmtp.rs/next/tuto/0/ssl-tls.html

**Expected behavior**

Normal startup of the server.

**Screenshots**

**System (please complete the following information):**
- vSMTP version: 
- OS: 
- OS version:

**Additional context**

I'm on Debian 11 with the deb package of vsmtp vesion 1.3.3 for ubuntu 20.04.

I've verified that the certificate files are readable both for the root user as well as the vsmtp ser.

My config:

    version_requirement = ">=1.3.3, <2.0.0"

    [server]
    domain = "mydomain.org"

    [server.interfaces]
    addr = ["88.99.82.182:25"]
    addr_submission = ["88.99.82.182:587"]
    addr_submissions = ["88.99.82.182:465"]

    # TLS settings
    [server.tls]
    security_level = "May"
    preempt_cipherlist = false
    handshake_timeout = "1000ms"
    protocol_version = ["TLSv1.2", "TLSv1.3"]
    certificate = "/data/ssl/mydomain.org.pem"
    private_key = "/data/ssl/mydomain.org.key"

**Comment by Mathieu-Lala** [comment]
Hi :wave: 

Is your certifiacte a X509 ? (it is the only format supported by [`rustls`](https://github.com/rustls/rustls))

**Comment by thomas-mc-work** [comment]
Thank you for your quick reply!

I double-checked the contents and realized that the file wasn't in the correct format, as I've simply extracted it from the acme.json of traefik. Maybe a more meaningful error message could help other user in a similar situation.

Thanks overall!

**Comment by Mathieu-Lala** [comment]
Great ! Thank for your issue :+1:
