### ISSUE TITLE
Beware of SQL injection

### ISSUE THREAD

**Issue by schungx** [viridIT/vSMTP#914]
**Describe the bug**
Your example code in the `README`:

```rust
if db::greylist.query(`SELECT * FROM greylist.sender WHERE address = '${sender}';`)
```

is prone to SQL injection attack because `sender` has not been sanitized.  Same with the `INSERT`.

**Comment by ltabis** [comment]
Hey @schungx !
Good catch ! I did add a warning in the book but not in the readme. Thanks for the report !
